openapi: 3.0.0
info:
    title: OpenAPI SFT ELMA365
    version: 1.0.0
paths:
    /AgreementProcess:
        post:
            summary: Метод получения текущего этапа согласования документа в 1С:ДО по guid документа ELMA365
            operationId: getStatusByGuid
            tags:
                - AgreementProcess
            requestBody:
              required: true
              content:
                 application/json: 
                  schema: 
                    required: 
                      - elma_id
                    properties: 
                      elma_id:
                        description: guid объекта ELMA365
                        type: string
                        format: uuid
            responses: 
              2XX:
                description: Успешный ответ от 1С:ДО
                content: 
                  application/json: 
                    schema: 
                      required: 
                        - elma_id
                        - process_is_active
                        - tasks
                      properties: 
                        elma_id:
                          description: guid объекта ELMA365
                          type: string
                          format: uuid
                          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
                        process_is_active:
                          description: Активность процесса
                          type: boolean
                        tasks:
                          $ref: '#/components/schemas/tasks'
              4XX: 
                description: Возврат ошибки
                content: 
                  application/json: 
                    schema:
                      required:
                        - elma_id 
                        - error
                      properties: 
                        elma_id:
                          description: guid объекта ELMA365
                          type: string
                          format: uuid
                          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
                        error:
                          description: Описание ошибки
                          type: string
                          example: Ошибка получения статуса. Документ по guid не найден.

components: 
  schemas: 
    task:
      type: object
      required: 
        - task
        - executor
        - due_date
      properties: 
        task:
          description: Наименование задачи
          type: string
          example: 12. Согласовать Новый лимит
        executor:
          description: Исполнитель
          type: string
          example: Согласующее лицо лимиты грейд В (ДВР)
        due_date:
          description: Срок исполнения
          type: string
          example: 2026-05-05T00:00:00
    tasks:
      type: array
      items:
        $ref: '#/components/schemas/task'

